INSERT INTO `tests` (`id`, `group`, `number`, `name`)
VALUES
  (1, 'server', 100, 'Create an h-entry post (form-encoded)'),
  (3, 'server', 101, 'Create an h-entry post with multiple categories (form-encoded)'),
  (9, 'server', 104, 'Create an h-entry with a photo referenced by URL (form-encoded)'),
  (34, 'server', 107, 'Create an h-entry post with one category (form-encoded)'),
  (2, 'server', 200, 'Create an h-entry post (JSON)'),
  (4, 'server', 201, 'Create an h-entry post with multiple categories (JSON)'),
  (33, 'server', 202, 'Create an h-entry with HTML content (JSON)'),
  (11, 'server', 203, 'Create an h-entry with a photo referenced by URL (JSON)'),
  (6, 'server', 204, 'Create an h-entry post with a nested object (JSON)'),
  (35, 'server', 205, 'Create an h-entry post with a photo with alt text (JSON)'),
  (7, 'server', 300, 'Create an h-entry with a photo (multipart)'),
  (8, 'server', 301, 'Create an h-entry with two photos (multipart)'),
  (12, 'server', 400, 'Replace a property'),
  (13, 'server', 401, 'Add a value to an existing property'),
  (19, 'server', 402, 'Add a value to a non-existent property'),
  (20, 'server', 403, 'Remove a value from a property'),
  (21, 'server', 404, 'Remove a property'),
  (22, 'server', 405, 'Reject the request if operation is not an array'),
  (14, 'server', 500, 'Delete a post (form-encoded)'),
  (15, 'server', 501, 'Delete a post (JSON)'),
  (16, 'server', 502, 'Undelete a post (form-encoded)'),
  (17, 'server', 503, 'Undelete a post (JSON)'),
  (23, 'server', 600, 'Configuration Query'),
  (24, 'server', 601, 'Syndication Endpoint Query'),
  (25, 'server', 602, 'Source Query (All Properties)'),
  (26, 'server', 603, 'Source Query (Specific Properties)'),
  (27, 'server', 700, 'Upload a jpg to the Media Endpoint'),
  (28, 'server', 701, 'Upload a png to the Media Endpoint'),
  (29, 'server', 702, 'Upload a gif to the Media Endpoint'),
  (30, 'server', 800, 'Accept access token in HTTP header'),
  (31, 'server', 801, 'Accept access token in POST body');
