INSERT INTO `tests` (`id`, `group`, `number`, `name`, `description`)
VALUES
  (1, 'server', 100, 'Create an h-entry post (form-encoded)', NULL),
  (2, 'server', 200, 'Create an h-entry post (JSON)', NULL),
  (3, 'server', 101, 'Create an h-entry post with multiple categories (form-encoded)', NULL),
  (4, 'server', 201, 'Create an h-entry post with multiple categories (JSON)', NULL),
  (6, 'server', 204, 'Create an h-entry post with a nested object (JSON)', NULL),
  (7, 'server', 300, 'Create an h-entry with a photo (multipart)', NULL),
  (8, 'server', 301, 'Create an h-entry with two photos (multipart)', NULL),
  (9, 'server', 104, 'Create an h-entry with a photo referenced by URL (form-encoded)', NULL),
  (11, 'server', 203, 'Create an h-entry with a photo referenced by URL (JSON)', NULL),
  (12, 'server', 400, 'Replace a property', NULL),
  (13, 'server', 401, 'Add a value to an existing property', NULL),
  (14, 'server', 500, 'Delete a post (form-encoded)', NULL),
  (15, 'server', 501, 'Delete a post (JSON)', NULL),
  (16, 'server', 502, 'Undelete a post (form-encoded)', NULL),
  (17, 'server', 503, 'Undelete a post (JSON)', NULL),
  (19, 'server', 402, 'Add a value to a non-existent property', NULL),
  (20, 'server', 403, 'Remove a value from a property', NULL),
  (21, 'server', 404, 'Remove a property', NULL),
  (22, 'server', 405, 'Reject the request if operation is not an array', NULL),
  (23, 'server', 600, 'Configuration Query', NULL),
  (24, 'server', 601, 'Syndication Endpoint Query', NULL),
  (25, 'server', 602, 'Source Query (All Properties)', NULL),
  (26, 'server', 603, 'Source Query (Specific Properties)', NULL),
  (27, 'server', 700, 'Upload a jpg to the Media Endpoint', NULL),
  (28, 'server', 701, 'Upload a png to the Media Endpoint', NULL),
  (29, 'server', 702, 'Upload a gif to the Media Endpoint', NULL),
  (30, 'server', 800, 'Accept access token in HTTP header', NULL),
  (31, 'server', 801, 'Accept access token in POST body', NULL),
  (33, 'server', 202, 'Create an h-entry with HTML content (JSON)', NULL),
  (34, 'server', 107, 'Create an h-entry post with one category (form-encoded)', NULL),
  (35, 'server', 205, 'Create an h-entry post with a photo with alt text (JSON)', NULL),
  (36, 'server', 206, 'Create an h-entry with multiple photos referenced by URL (JSON)', NULL),
  (37, 'server', 802, 'Does not store access token property', NULL),
  (38, 'server', 803, 'Rejects unauthenticated requests', NULL),
  (39, 'server', 804, 'Rejects unauthorized access tokens', NULL),
  (40, 'client', 100, 'Create an h-entry post (form-encoded)', '      <p>This is a basic test of creating an h-entry post from your client in form-encoded format.</p>\n      <p>To pass this test, use your client to create an h-entry post with plain text content. It doesn\'t matter what text you send.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (41, 'client', 200, 'Create an h-entry post (JSON)', '      <p>This is a basic test of creating an h-entry post from your client in JSON format.</p>\n      <p>To pass this test, use your client to create an h-entry post with plain text content. It doesn\'t matter what text you send.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (42, 'client', 101, 'Create an h-entry post with multiple categories (form-encoded)', '      <p>This is a test of creating an h-entry post from your client in form-encoded format with multiple properties of the same name.</p>\n      <p>To pass this test, use your client to create an h-entry post with multiple categories. It doesn\'t matter what text you send as the content, or what category names you use.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (43, 'client', 201, 'Create an h-entry post with multiple categories (JSON)', '      <p>This is a test of creating an h-entry post from your client in JSON format with multiple values of a property.</p>\n      <p>To pass this test, use your client to create an h-entry post with multiple categories. It doesn\'t matter what text you send as the content, or what category names you use.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (44, 'client', 104, 'Create an h-entry with a photo referenced by URL (form-encoded)', '      <p>This is a test of creating an h-entry post from your client in form-encoded format, including a photo referenced by URL.</p>\n      <p>To pass this test, use your client to create an h-entry post including a \"photo\" parameter referencing a URL. Typically this is the flow when the user chooses a photo and the client uploads it to their media endpoint.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (45, 'client', 203, 'Create an h-entry with a photo referenced by URL (JSON)', '       <p>This is a test of creating an h-entry post from your client in JSON format, including a photo referenced by URL.</p>\n      <p>To pass this test, use your client to create an h-entry post including a \"photo\" parameter referencing a URL. Typically this is the flow when the user chooses a photo and the client uploads it to their media endpoint.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (46, 'client', 204, 'Create an h-entry including a nested Microformats2 object (JSON)', '       <p>This is a test of creating an h-entry post from your client in JSON format, including a nested Microformats2 object.</p>\n      <p>To pass this test, use your client to create an h-entry post including any other property whose value is another Microformats object. Typical uses of this would be including a nested h-card to tag a photo with a person, or including an h-item object in an h-review.</p>'),
  (47, 'client', 205, 'Create an h-entry with a photo including image alt text', '      <p>This is a test of creating an h-entry post including a photo with alt text.</p>\n      <p>To pass this test, use your client to create an h-entry post including a \"photo\" parameter referencing a photo URL as well as the alt text. See <a href=\"https://www.w3.org/TR/micropub/#uploading-a-photo-with-alt-text\">section 3.3.2</a> for an example of the syntax.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>'),
  (48, 'client', 300, 'Create an h-entry with a photo (Multipart)', '       <p>This is a test of creating an h-entry post from your client including uploading a photo. This request must be sent in Multipart format.</p>\n      <p>Keep this page open and post from your client. Your post will appear here.</p>');


INSERT INTO `features` (`number`, `description`)
VALUES
  (1, 'Discovering the Micropub endpoint given the profile URL of a user'),
  (2, 'Authenticating requests by including the access token in the HTTP Authorization header'),
  (3, 'Authenticating requests by including the access token in the post body for x-www-form-urlencodedrequests'),
  (4, 'Limiting the ability to create posts given an access token by requiring that the access token contain at least one OAuth 2.0 scope value'),
  (5, 'Creating a post using x-www-form-urlencoded syntax with one or more properties'),
  (6, 'Creating a post using JSON syntax with one or more properties'),
  (7, 'Creating a post using x-www-form-urlencoded syntax with multiple values of the same property name'),
  (8, 'Creating a post using JSON syntax with multiple values of the same property name'),
  (9, 'Creating a post using JSON syntax including a nested Microformats2 object'),
  (10, 'Uploading a file to the specified Media Endpoint'),
  (11, 'Creating a post with a file by sending the request as multipart/form-data to the Micropub endpoint'),
  (12, 'Creating a post with a photo referenced by URL'),
  (13, 'Creating a post with a photo referenced by URL that includes image alt text'),
  (14, 'Returning HTTP 201 Created and a Location header when creating a post'),
  (15, 'Returning HTTP 202 Created and a Location header when creating a post'),
  (16, 'Updating a post and replacing all values of a property'),
  (17, 'Updating a post and adding a value to a property'),
  (18, 'Updating a post and removing a value from a property'),
  (19, 'Updating a post and removing a property'),
  (20, 'Returning HTTP 200 OK when updating a post'),
  (21, 'Returning HTTP 201 Created when updating a post if the update cause the post URL to change'),
  (22, 'Returning HTTP 204 No Content when updating a post'),
  (23, 'Deleting a post using x-www-form-urlencoded syntax'),
  (24, 'Deleting a post using JSON syntax'),
  (25, 'Undeleting a post using x-www-form-urlencoded syntax'),
  (26, 'Undeleting a post using JSON syntax'),
  (27, 'Uploading a photo to the Media Endpoint and using the resulting URL when creating a post'),
  (28, 'Querying the Micropub endpoint with q=config to retrieve the Media Endpoint and syndication targets if specified'),
  (29, 'Querying the Micropub endpoint with q=syndicate-to to retrieve the list of syndication targets'),
  (30, 'Querying the Micropub endpoint for a post\'s source content without specifying a list of properties'),
  (31, 'Querying the Micropub endpoint for a post\'s source content looking only for specific properties'),
  (32, 'Creating a post using x-www-form-urlencoded syntax with a single value for a property that normally accepts multiple values'),
  (33, 'Updating a post and adding a property');

