#!/bin/bash
set -e

BASE_PATH=$(cd $(dirname $0)/.. && pwd)
cd $BASE_PATH

if [ -f "$BASE_PATH/lib/config.php" ]; then
  SITEURL=$(grep base $BASE_PATH/lib/config.php | cut -d\' -f2 | cut -d/ -f3)
  SITENAME=$(echo "$SITEURL" | cut -d: -f1)
  _port=$( echo "$SITEURL" | awk -F: '{ print $2 }' )
  PORT=${_post:-80}
  DBNAME=$(grep dbname $BASE_PATH/lib/config.php | cut -d\' -f2)
  DBUSER=$(grep dbuser $BASE_PATH/lib/config.php | cut -d\' -f2)
  DBPASS=$(grep dbpass $BASE_PATH/lib/config.php | cut -d\' -f2)
else
  echo "Copy `lib/config.template.php` to `lib/config.php`, customise and run this again."
  exit 1
fi

echo "=> Installing PHP packages..."
composer.phar install

echo "=> Setting up database (you'll be prompted for the MySQL root user's password)..."
mysql -u root -p -e "CREATE USER IF NOT EXISTS '$DBUSER'@'localhost' IDENTIFIED BY '$DBPASS'; DROP DATABASE IF EXISTS $DBNAME; CREATE DATABASE $DBNAME; GRANT ALL PRIVILEGES ON $DBNAME.* TO '$DBUSER'@'localhost' IDENTIFIED BY '$DBPASS'"

echo "==> Importing SQL data..."
mysql -u $DBUSER -p$DBPASS $DBNAME < $BASE_PATH/database/schema.sql
mysql -u $DBUSER -p$DBPASS $DBNAME < $BASE_PATH/database/data.sql

echo "==> Creating .htaccess..."
cat <<EOF > .htaccess
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
EOF

echo "==> Creating Apache vhost config... (you'll be prompted for your password)"
cat <<EOF > vhost.conf
<VirtualHost *:$PORT>
  DocumentRoot "$BASE_PATH/public"
  ServerName $SITENAME
  <Directory $BASE_PATH>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
EOF
sudo ln -s "$BASE_PATH/vhost.conf" "/etc/apache2/other/vhost-$SITENAME.conf"
sudo apachectl restart

echo "==> Checking Apache config..."
echo "  PHP enabled?      [$(apachectl -M | grep -iq php && echo OK || echo FAIL)]"
echo "  Rewrite enabled?  [$(apachectl -M | grep -iq rewrite && echo OK || echo FAIL)]"
echo "  Vhost enabled?    [$(apachectl -M | grep -iq vhost && echo OK || echo FAIL)]"

echo
echo "==> All done <=="
echo
echo "You'll need to manually correct anything that failed above."