#!/bin/bash
set -e

BASE_PATH=$(cd $(dirname $0)/.. && pwd)
cd $BASE_PATH

if [ -f "$BASE_PATH/lib/config.php" ]; then
  SITEURL=$(grep base $BASE_PATH/lib/config.php | cut -d\' -f2 | cut -d/ -f3)
  SITENAME=$(echo "$SITEURL" | cut -d: -f1)
  PORT=":$(echo "$SITEURL" | cut -d: -f2)"
  DBNAME=$(grep dbname $BASE_PATH/lib/config.php | cut -d\' -f2)
  DBUSER=$(grep dbuser $BASE_PATH/lib/config.php | cut -d\' -f2)
  DBPASS=$(grep dbpass $BASE_PATH/lib/config.php | cut -d\' -f2)
else
  echo "Copy `lib/config.template.php` to `lib/config.php`, customise and run this again."
  exit 1
fi

echo "=> Installing PHP packages..."
#composer install

echo "=> Setting up database (you'll be prompted for the MySQL root user's password)..."
mysql -u root -p -e "CREATE USER IF NOT EXISTS '$DBUSER'@'localhost' IDENTIFIED BY '$DBPASS'; DROP DATABASE IF EXISTS $DBNAME; CREATE DATABASE $DBNAME; GRANT ALL PRIVILEGES ON $DBNAME.* TO '$DBUSER'@'localhost' IDENTIFIED BY '$DBPASS'"

echo "==> Importing SQL data..."
mysql -u $DBUSER -p$DBPASS $DBNAME < $BASE_PATH/database/schema.sql
mysql -u $DBUSER -p$DBPASS $DBNAME < $BASE_PATH/database/data.sql

echo "==> Creating .htaccess..."
cat <<EOF > .htaccess
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ public/index.php [QSA,L]
EOF

echo
echo "==> All done <=="
echo
cat <<EOF
Create a new vhost configuration with the following content (assumes Apache):

<VirtualHost *$PORT>
  DocumentRoot "$BASE_PATH/public"
  ServerName $SITENAME
  <Directory $BASE_PATH/public>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
EOF
